import {afterEach,describe,it,expect,vi} from 'vitest'
import {generatePlans,understandTrip,selectPlanOption,readSavedPlans,writeSavedPlan,undoPlanEdit} from './planner'
import {TripGenerationJob,readGenerationJob} from './generationJob'
import type {AIService} from '../ai'
import {writeVersioned,readVersioned} from '../storage'
import {previewTripDuration} from './editDuration'
import {shareSnapshot} from './shareSnapshot'
import {canNavigatePlace} from '../mapLauncher'
import {groupDietary} from './groupTrip'
import {emptyDietaryProfile} from './dietary'
import type {GroupPlan} from '../groupPlans'

afterEach(()=>vi.unstubAllGlobals())
const request={text:'2026年9月11日到9月13日去成都3天，1人，人均预算1000元。',media:[]}
function setup(){const local=new Map<string,string>(),session=new Map<string,string>();const storage=(values:Map<string,string>)=>({getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value)});vi.stubGlobal('window',{dispatchEvent:vi.fn(),localStorage:storage(local),sessionStorage:storage(session)});return {local,session}}
describe('task01 Trip identity and generation contracts',()=>{
  it('A06 previews allocate no Trip; choosing variants updates one generation Trip and keeps other generations',()=>{setup();const plans=generatePlans(understandTrip(request).intent);expect(plans.every(plan=>!plan.tripId)).toBe(true);expect(readSavedPlans()).toBeNull();const saved=selectPlanOption(plans[0]);expect(selectPlanOption(plans[1]).tripId).toBe(saved.tripId);expect(readSavedPlans()).toHaveLength(1);selectPlanOption(generatePlans(understandTrip(request).intent)[0]);expect(readSavedPlans()).toHaveLength(2)})
  it('A06 cannot replace an active Trip or save an experience example',()=>{setup();const options=generatePlans(understandTrip(request).intent);const saved=selectPlanOption(options[0]);writeSavedPlan({...saved,status:'active',revision:2});expect(()=>selectPlanOption(options[1])).toThrow('已开始');expect(()=>selectPlanOption({...options[0],example:true})).toThrow('体验示例')})
  it('A05 late old response cannot overwrite the new job or its result',async()=>{setup();const result=understandTrip(request);let finish!:(value:typeof result)=>void;const service={understandTrip:vi.fn(()=>new Promise(resolve=>{finish=resolve})),generatePlans:vi.fn()} as unknown as AIService;const old=new TripGenerationJob(request,service);const oldWork=old.understand(()=>{});const next=new TripGenerationJob({...request,text:'去南京1天'}, {...service,understandTrip:async()=>result} as AIService);await next.understand(()=>{});finish(result);await expect(oldWork).rejects.toMatchObject({name:'AbortError'});expect(readGenerationJob()?.id).toBe(next.record.id)})
  it('A07 duration preview preserves saved identity and start date while recalculating nights and costs',()=>{setup();const plan=selectPlanOption(generatePlans(understandTrip(request).intent)[0]);const changed=previewTripDuration(plan,4);expect(changed.tripId).toBe(plan.tripId);expect(changed.dates).toEqual({start:'2026-09-11',end:'2026-09-14'});expect(changed.nights).toBe(3);expect(changed.budgetBreakdown.lodging).toBeGreaterThan(plan.budgetBreakdown.lodging);expect(readSavedPlans()?.[0].nights).toBe(2)})
  it('A10 migrates only the selected legacy row once and backs up identical historical rows',()=>{setup();const original=generatePlans(understandTrip(request).intent)[0];const legacy={...original,optionId:undefined,generationId:undefined};writeVersioned('zouzou-saved-plans-v1',[legacy,legacy],'local');const selected=readSavedPlans()![0];const migrated=writeSavedPlan(selected);expect(readSavedPlans()).toHaveLength(2);expect(readSavedPlans()?.filter(plan=>!plan.tripId)).toHaveLength(1);writeSavedPlan(migrated);expect(readSavedPlans()).toHaveLength(2);expect(readVersioned<unknown[]>('zouzou-trip-id-migration-backup-v3','local')).toHaveLength(2)})
  it('A07 undo duration restores dates, nights, original arrangements and lodging cost together',()=>{const plan=generatePlans(understandTrip(request).intent)[0];const reverted=undoPlanEdit(previewTripDuration(plan,2));expect(reverted.dates).toEqual(plan.dates);expect(reverted.nights).toBe(plan.nights);expect(reverted.intent).toEqual(plan.intent);expect(reverted.days).toEqual(plan.days);expect(reverted.budgetBreakdown.lodging).toBe(plan.budgetBreakdown.lodging)})
  it('A15 snapshot excludes original notes, hotel and transport anchors and keeps real dates',()=>{const plan=generatePlans(understandTrip(request).intent)[0];Object.values(plan.days).flat().forEach(stop=>stop.note='PRIVATE-ORDER');const snapshot=shareSnapshot(plan);expect(JSON.stringify(snapshot)).not.toContain('PRIVATE-ORDER');expect(Object.values(snapshot.days).flat().every(stop=>!['住宿','到达','返程'].includes(stop.type))).toBe(true);expect(snapshot.title).toBe('成都 · 3天2晚');expect(snapshot.dates?.start).toBe('2026-09-11')})
  it('A16 blocks city-only and unresolved anchors while allowing explicit complete addresses',()=>{expect(canNavigatePlace({id:'city',name:'成都'},'成都')).toBe(false);expect(canNavigatePlace({id:'unknown',name:'某家店',mapStatus:'unresolved'},'成都')).toBe(false);expect(canNavigatePlace({id:'poi',name:'成都博物馆',address:'四川省成都市青羊区小河街1号'},'成都')).toBe(true)})
  it('A14 keeps original travel allergies without retaining a departed member restriction',()=>{const plan={type:'travel',avoidTags:[],baseDietary:{...emptyDietaryProfile(),allergies:['花生']},participants:[{inviteStatus:'accepted',foodPreferences:['牛奶过敏']}]} as unknown as GroupPlan;expect(groupDietary(plan).allergies).toContain('花生');expect(groupDietary(plan).allergies).toContain('牛奶');plan.participants=[];expect(groupDietary(plan).allergies).toEqual(['花生'])})
})

