import { FormSelect } from '../components/FormSelect'
import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { CommunityFeed } from '../components/CommunityFeed'
import { communityApi, type CommunityPost, type CommunityComment } from '../services/community'
import { AppShell } from '../components/AppShell'
import { ZouNavigationBar } from '../components/ui'
import { MediaAsset } from '../components/MediaAsset'
import { useSavedTrips } from '../components/TripLibrary'
import { readPublications, publicationDraft, savePublication, type LocalPublication } from '../services/publications'
import { tripSummary } from '../services/trip/summary'
import { useAppStore } from '../stores/appStore'

export function usePublications() {
  const [items,setItems]=useState(readPublications)
  useEffect(()=>{const reload=()=>setItems(readPublications());window.addEventListener('storage',reload);window.addEventListener('zouzou-publications-updated',reload);return()=>{window.removeEventListener('storage',reload);window.removeEventListener('zouzou-publications-updated',reload)}},[])
  return items
}
export function PublicationList({feed=false}:{feed?:boolean}) {
  const navigate=useNavigate(),items=usePublications().filter(item=>feed?item.status==='published':!item.publicRevision||item.status==='draft')
  const legacy=useAppStore(state=>state.publishedPosts)
  if (feed) return <CommunityFeed />
  return <><CommunityFeed initialMode="mine" controls={false}/><section aria-label="本机发布"><p>仅此设备可见，尚未发布到公共社区。</p>{!feed?<button onClick={()=>navigate('/discover/publish')}>从我的行程生成发布草稿</button>:null}{items.map(item=><article className="trip-record" key={item.id}><button className="trip-record__open" onClick={()=>navigate(item.status==='draft'?`/discover/publish?edit=${item.id}`:`/publications/${item.id}`)}><strong>{item.title}</strong><p>{item.city} · {item.experience==='experienced'?'已体验':'计划中'} · {item.status==='draft'?'草稿':item.status==='published'?'本机展示':'已撤回'}</p></button>{!feed?<button onClick={()=>navigate(`/discover/publish?edit=${item.id}`)}>编辑</button>:null}</article>)}{!feed&&legacy.length?<details><summary>旧版本机发布（{legacy.length}）</summary><p>原记录保留在此设备，未转为公共内容。</p>{legacy.map(post=><button className="sheet-row" key={post.id} onClick={()=>navigate(`/discover/post-${post.routeId}-shared`)}>{post.title} · {post.publishedAt.slice(0,10)}</button>)}</details>:null}</section></>
}
export function PublicationEditor() {
  const navigate=useNavigate(),plans=useSavedTrips(),[params]=useSearchParams(),nickname=useAppStore(state=>state.nickname)
  const [draft,setDraft]=useState<LocalPublication|undefined>(()=>readPublications().find(item=>item.id===params.get('edit'))),[error,setError]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(params.get('public')==='1')
  const operation=useRef<{fingerprint:string;id:string}|null>(null)
  const canDescribeExperience=draft?.experience==='experienced'||plans.some(plan=>plan.tripId===draft?.tripId&&plan.status==='completed')
  useEffect(()=>{if(params.get('public')!=='1'||!params.get('edit'))return;const controller=new AbortController();setLoading(true);communityApi.get(params.get('edit')!,controller.signal).then(item=>{if(!item.owned)throw Error('只有作者可以编辑');const local=readPublications().find(value=>value.id===item.id);setDraft({...item,tripId:local?.tripId??'',tripRevision:local?.tripRevision??0,dates:local?.dates??'',revision:local?.revision??0,publicRevision:item.revision,status:'draft'})}).catch(cause=>{if(!controller.signal.aborted)setError(String(cause))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[params])
  const save=()=>{if(!draft)return;try{setDraft(savePublication({...draft,status:'draft'}));setError('草稿已保存在本机')}catch(cause){setError(String(cause))}}
  const publish=async()=>{
    if(!draft||busy)return;setBusy(true);setError('')
    const content={title:draft.title,body:draft.body,city:draft.city,cover:draft.cover,experience:draft.experience,season:draft.season??'',audience:draft.audience??'',stops:draft.stops}
    const fingerprint=JSON.stringify({content,nickname,revision:draft.publicRevision??0})
    if(operation.current?.fingerprint!==fingerprint)operation.current={fingerprint,id:crypto.randomUUID()}
    try { const published=await communityApi.publish(draft.id,draft.publicRevision??0,operation.current.id,nickname||'设备访客',content)
      const next={...draft,publicRevision:published.revision,status:'published' as const};setDraft(next);setPreview(false);operation.current=null
      try{setDraft(savePublication(next));setError('已发布到当前服务的公开社区，其他访客可查看。')}catch{setError('社区发布已成功，但本机副本保存失败。可在我的社区记录中继续编辑。')}
    } catch(cause){setError(String(cause))}finally{setBusy(false)}
  }
  if(loading)return <AppShell><p role="status">正在读取发布版本…</p></AppShell>
  return <AppShell><ZouNavigationBar title="发布行程记录"/><main className="page-content journey-form-page">{!draft?<><h1>选择要整理的行程</h1>{plans.map(plan=><button className="sheet-row" key={plan.tripId} onClick={()=>setDraft(publicationDraft(plan))}>{tripSummary(plan).title} · {tripSummary(plan).dates}</button>)}{!plans.length?<button onClick={()=>navigate('/travel/new')}>创建并保存行程</button>:null}</>:<><p>{draft.city}{draft.tripRevision?` · 来源版本${draft.tripRevision}`:''}</p><p>编辑发布内容不会修改私人行程。确认发布后，同一服务中的其他访客可见。作者身份绑定当前浏览器会话。</p><fieldset disabled={busy}><label>发布标题<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} maxLength={80}/></label><label>正文<textarea aria-label="正文" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} maxLength={3000}/></label><label>体验状态<FormSelect value={draft.experience} onChange={e=>setDraft({...draft,experience:e.target.value as LocalPublication['experience']})}><option value="planned">计划中，尚未体验</option><option value="experienced" disabled={!canDescribeExperience}>已体验</option></FormSelect></label>{!canDescribeExperience?<p>当前行程尚未完成，发布为计划；行程完成后可记录实地体验。</p>:null}<label>适用季节（选填）<input value={draft.season??''} maxLength={50} onChange={e=>setDraft({...draft,season:e.target.value})}/></label><label>适合人群（选填）<input value={draft.audience??''} maxLength={80} onChange={e=>setDraft({...draft,audience:e.target.value})}/></label><label>封面<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>450000){setError('封面不超过450KB，请压缩后再选择');return}const reader=new FileReader();reader.onerror=()=>setError('图片读取失败，原封面保留');reader.onload=()=>setDraft(value=>value?{...value,cover:String(reader.result)}:value);reader.readAsDataURL(file)}}/></label><button onClick={save}>保存草稿</button><button disabled={!draft.title.trim()||!draft.body.trim()} onClick={()=>setPreview(true)}>预览发布内容</button>{draft.publicRevision?<button onClick={()=>navigate(`/publications/${draft.id}?public=1`)}>查看社区记录</button>:null}{preview?<section aria-label="发布隐私预览"><MediaAsset city={draft.city} src={draft.cover}/><h2>{draft.title}</h2><p>{draft.body}</p><p>{draft.city} · {draft.season||'季节未限定'} · {draft.audience||'人群未限定'}</p><p>作者：{nickname||'设备访客'} · {draft.experience==='experienced'?'已体验':'计划中'} · 公开社区</p><p>不包含票据、私人备注、住宿和到离信息。以下地点名称会保留，请逐项检查；正文、图片与昵称也会公开。</p>{draft.stops.map((stop,i)=><p key={i}>{stop.day} · {stop.time} · {stop.name}<button aria-label={`移除公开地点${stop.name}`} onClick={()=>setDraft({...draft,stops:draft.stops.filter((_,index)=>index!==i)})}>移除</button></p>)}<button onClick={()=>void publish()}>{busy?'正在发布…':'确认公开发布'}</button><button onClick={()=>setPreview(false)}>继续修改</button></section>:null}</fieldset></>}{error?<p role="status">{error}</p>:null}</main></AppShell>
}

function PublicDetail({id}:{id:string}) {
  const navigate=useNavigate(),nickname=useAppStore(state=>state.nickname),[item,setItem]=useState<CommunityPost>(),[comments,setComments]=useState<CommunityComment[]>([]),[nextOffset,setNextOffset]=useState<number|null>(null),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0)
  const commentRequest=useRef<{body:string;id:string}|null>(null)
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setItem(undefined);setComments([]);communityApi.get(id,controller.signal).then(async post=>{setItem(post);if(post.status==='published'){const page=await communityApi.comments(id,0,controller.signal);setComments(page.items);setNextOffset(page.nextOffset)}}).catch(cause=>{if(!controller.signal.aborted)setError(String(cause))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[id,retry])
  const act=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await work()}catch(cause){setError(String(cause))}finally{setBusy(false)}}
  const refreshComments=async()=>{const page=await communityApi.comments(id);setComments(page.items);setNextOffset(page.nextOffset);setItem(await communityApi.get(id))}
  return <AppShell><ZouNavigationBar title="公开行程记录"/><main className="page-content journey-form-page">{loading?<p role="status">正在读取记录…</p>:null}{item?<><MediaAsset city={item.city} src={item.cover}/><h1>{item.title}</h1><p>{item.nickname} · {item.experience==='experienced'?'已体验':'计划中'} · 版本{item.revision}</p><p>{item.body}</p><p>{item.city} · {item.season||'季节未限定'} · {item.audience||'人群未限定'}</p><p>公开社区 · 当前服务可见 · 更新于{new Date(item.updatedAt).toLocaleString('zh-CN')}</p>{item.stops.map((stop,i)=><p key={i}>{stop.day} · {stop.time} · {stop.name}</p>)}{item.owned?<><button onClick={()=>navigate(`/discover/publish?edit=${id}&public=1`)}>编辑新版本</button>{item.status==='published'?<button disabled={busy} onClick={()=>void act(async()=>{const result=await communityApi.retract(id,item.revision);setItem({...item,status:'retracted',revision:result.revision});setComments([])})}>撤回公开记录</button>:<p>已撤回，其他访客无法再查看。</p>}</>:null}{item.status==='published'?<><div><button disabled={busy} aria-pressed={item.liked} onClick={()=>void act(async()=>setItem(await communityApi.react(id,'like',!item.liked)))}>{item.liked?'取消点赞':'点赞'}（{item.likes}）</button><button disabled={busy} aria-pressed={item.saved} onClick={()=>void act(async()=>setItem(await communityApi.react(id,'favorite',!item.saved)))}>{item.saved?'取消社区收藏':'收藏到社区'}（{item.favorites}）</button>{!item.owned?<button disabled={busy} aria-pressed={item.following} onClick={()=>void act(async()=>{await communityApi.follow(item.authorId,!item.following);setItem({...item,following:!item.following})})}>{item.following?'取消关注':'关注作者'}</button>:null}</div><h2>评论（{item.commentCount}）</h2>{comments.map(comment=><article key={comment.id}><strong>{comment.nickname}</strong><p>{comment.body}</p>{comment.owned?<button disabled={busy} onClick={()=>void act(async()=>{await communityApi.removeComment(id,comment.id);await refreshComments()})}>删除我的评论</button>:null}</article>)}{nextOffset!==null?<button disabled={busy} onClick={()=>void act(async()=>{const page=await communityApi.comments(id,nextOffset);setComments(previous=>[...previous,...page.items.filter(value=>!previous.some(old=>old.id===value.id))]);setNextOffset(page.nextOffset)})}>更多评论</button>:null}<label>写评论<textarea aria-label="写评论" value={body} maxLength={1000} disabled={busy} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy||!body.trim()} onClick={()=>void act(async()=>{if(commentRequest.current?.body!==body)commentRequest.current={body,id:crypto.randomUUID()};await communityApi.comment(id,commentRequest.current.id,body,nickname||'设备访客');setBody('');commentRequest.current=null;await refreshComments()})}>发布评论</button></>:null}</>:null}{error?<p role="alert">{error}<button onClick={()=>setRetry(value=>value+1)}>重新读取</button></p>:null}</main></AppShell>
}
export function PublicationDetail() {
  const {id}=useParams(),[params]=useSearchParams(),navigate=useNavigate(),item=usePublications().find(item=>item.id===id),[error,setError]=useState(''),nickname=useAppStore(state=>state.nickname)
  if(id&&(params.get('public')==='1'||!item||item.publicRevision))return <PublicDetail key={id} id={id}/>
  return <AppShell><ZouNavigationBar title="本机行程记录"/><main className="page-content">{!item||item.status!=='published'?<p>内容未发布、已撤回或不属于此设备。</p>:<><MediaAsset city={item.city} src={item.cover}/><h1>{item.title}</h1><p>{nickname} · {item.experience==='experienced'?'已体验':'计划中'} · 本机版本{item.revision}</p><p>{item.body}</p><p>旧版本机记录，仅此设备可见。</p>{item.stops.map((stop,i)=><p key={i}>{stop.day} · {stop.time} · {stop.name}</p>)}<button onClick={()=>navigate(`/discover/publish?edit=${item.id}`)}>编辑新版本</button><button onClick={()=>{try{savePublication({...item,status:'retracted'})}catch(cause){setError(String(cause))}}}>撤回本机展示</button></>}{error?<p role="alert">{error}</p>:null}</main></AppShell>
}
