import { readFile, writeFile, mkdir, stat } from 'node:fs/promises'
import { execFileSync } from 'node:child_process'
import { discoverItems, routes } from '../src/demo-data/discover'
import { cityImages, getCityImageGallery } from '../src/demo-data/city-images'
import { acquiredJourneyImages } from '../src/demo-data/acquired-journey-images'
import { createHash } from 'node:crypto'

const paths=new Set<string>()
function visit(value:unknown) {
  if(typeof value==='string') {if(/^\/assets\/[^?]+\.(?:png|jpe?g|webp|svg|gif|ttf|woff2?|mp4|json)$/i.test(value))paths.add(value)}
  else if(Array.isArray(value))value.forEach(visit)
  else if(value&&typeof value==='object')Object.values(value).forEach(visit)
}
visit(discoverItems);visit(routes);visit(cityImages)
for(const city of Object.keys(cityImages))visit(getCityImageGallery(city))
visit(JSON.parse(await readFile('data/journey-images/approved-cover-paths-2026-09-14.json','utf8')))
const files=execFileSync('rg',['--files','src','public','--glob','!public/assets/**'],{encoding:'utf8'}).trim().split(/\r?\n/)
for(const file of files) {
  if(!/\.(tsx?|css|html|webmanifest)$/.test(file)||/acquired-journey-images|discover-cover-index|JourneyImageReviewPage|\.test\./.test(file))continue
  const text=await readFile(file,'utf8')
  for(const match of text.matchAll(/["'`(](\/assets\/[^"'`\s){}]+\.(?:png|jpe?g|webp|svg|gif|ttf|woff2?))["'`)]/gi))paths.add(match[1])
}
for(const name of ['icon-192.png','icon-512.png','maskable-512.png','apple-touch-icon.png','favicon-32.png'])paths.add('/assets/pwa/'+name)
const records=[];let bytes=0
for(const path of [...paths].sort()) {
  try {const info=await stat('public'+path);if(info.size>25*1024*1024)throw Error('Asset exceeds Pages file limit: '+path);records.push({path,bytes:info.size});bytes+=info.size}
  catch(cause) {if((cause as NodeJS.ErrnoException).code!=='ENOENT')throw cause}
}
const existing=new Set(records.map(item=>item.path))
const compact=acquiredJourneyImages.filter(image=>existing.has(image.localPath)).map(image=>{
  const clean={...image}
  for(const key of ['sourceUrl','originalUrl','noteUrl'] as const)if(clean[key]){try{const url=new URL(clean[key]!);for(const name of [...url.searchParams.keys()])if(/token|auth|signature|credential|expires/i.test(name))url.searchParams.delete(name);clean[key]=url.toString()}catch{/* keep source text */}}
  return clean
})
await mkdir('data/release',{recursive:true})
await writeFile('data/release/assets.json',JSON.stringify({permissionDeclaration:'docs/CONTENT-AUTHORIZATION.md',files:records,totalBytes:bytes},null,2)+'\n')
await writeFile('src/demo-data/acquired-journey-images.release.ts',"// Runtime-only image catalog; generated by prepare-release-assets.ts. Raw acquisition ledger stays local.\nimport type { AcquiredJourneyImage } from './acquired-journey-images'\nexport const acquiredJourneyImages = "+JSON.stringify(compact)+" as AcquiredJourneyImage[]\n")
const dataFiles=execFileSync('rg',['--files','data','--glob','*.json'],{encoding:'utf8'}).trim().split(/\r?\n/).filter(path=>/^(data[\\/](travel-guides(?:-reviewed-20-cities)?\.json|travel-kb-release\.json|travel-experience-(policy|reviewed)\.json|travel-research[\\/](2026-09-06-restaurants|reviewed-meal-venues|grounded-meal-venues|meal-web-supplement|destination-expansion-reviewed|three-platform-reviewed-routes|three-platform-named-places)\.json))$/.test(path)).sort()
const hash=createHash('sha256');const inputs=[]
for(const path of dataFiles){const bytes=await readFile(path);hash.update(path.replaceAll('\\','/'));hash.update(bytes);inputs.push({path:path.replaceAll('\\','/'),sha256:createHash('sha256').update(bytes).digest('hex')})}
if(dataFiles.length<10)throw Error('Incomplete runtime knowledge dependency list')
const kb=JSON.parse(await readFile('data/travel-guides-reviewed-20-cities.json','utf8'))
const release={knowledgeVersion:'travel-20260914-'+hash.digest('hex').slice(0,16),permissionDeclaration:'docs/CONTENT-AUTHORIZATION.md',approvalBasis:'owner-confirmed',reviewedCount:kb.guides.length,cities:[...new Set(kb.guides.map((guide:{city:string})=>guide.city))].length,sourceGeneratedAt:kb.generatedAt,inputs}
await writeFile('data/release/knowledge.json',JSON.stringify(release,null,2)+'\n')
console.log(JSON.stringify({assets:records.length,bytes,catalog:compact.length,knowledgeVersion:release.knowledgeVersion,reviewed:release.reviewedCount,cities:release.cities}))
