import type { CityImage } from './city-images'

type CityCoverSeed = { file: string; title: string; sourceUrl: string; downloadUrl: string; landmark?: string }

/** Additional landmark photos used to keep every city feed visually distinct. */
export const cityCoverSeeds: Record<string, CityCoverSeed[]> = {
  '上海': [
    { file: '/assets/locations/shanghai-cover-01.jpg', title: '20260209 129 Wukang Road.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260209%20129%20Wukang%20Road.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/20260209_129_Wukang_Road.jpg/1280px-20260209_129_Wukang_Road.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shanghai-cover-02.jpg', title: '20260209 109 Wukang Road.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260209%20109%20Wukang%20Road.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/20260209_109_Wukang_Road.jpg/1280px-20260209_109_Wukang_Road.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shanghai-cover-03.jpg', title: '20260209 105 Wukang Road.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260209%20105%20Wukang%20Road.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/20260209_105_Wukang_Road.jpg/1280px-20260209_105_Wukang_Road.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '杭州': [
    { file: '/assets/locations/hangzhou-cover-01.jpg', title: 'West Lake, Xihu, Hangzhou, Zhejiang, China - Flickr - Stuart Smith..jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWest%20Lake%2C%20Xihu%2C%20Hangzhou%2C%20Zhejiang%2C%20China%20-%20Flickr%20-%20Stuart%20Smith..jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/West_Lake%2C_Xihu%2C_Hangzhou%2C_Zhejiang%2C_China_-_Flickr_-_Stuart_Smith..jpg/1280px-West_Lake%2C_Xihu%2C_Hangzhou%2C_Zhejiang%2C_China_-_Flickr_-_Stuart_Smith..jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/hangzhou-cover-02.jpg', title: 'West Lake in Hangzhou.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWest%20Lake%20in%20Hangzhou.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/West_Lake_in_Hangzhou.jpg/1280px-West_Lake_in_Hangzhou.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/hangzhou-cover-03.jpg', title: 'West Lake- Hangzhou- China 1.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWest%20Lake-%20Hangzhou-%20China%201.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/West_Lake-_Hangzhou-_China_1.jpg/1280px-West_Lake-_Hangzhou-_China_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '苏州': [
    { file: '/assets/locations/suzhou-cover-01.jpg', title: 'Classical Gardens of Suzhou pavilion, August 2016.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AClassical%20Gardens%20of%20Suzhou%20pavilion%2C%20August%202016.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Classical_Gardens_of_Suzhou_pavilion%2C_August_2016.jpg/1280px-Classical_Gardens_of_Suzhou_pavilion%2C_August_2016.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/suzhou-cover-02.jpg', title: 'Classical Gardens of Suzhou-111933.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AClassical%20Gardens%20of%20Suzhou-111933.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Classical_Gardens_of_Suzhou-111933.jpg/1280px-Classical_Gardens_of_Suzhou-111933.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/suzhou-cover-03.jpg', title: 'Classical Gardens of Suzhou-111931.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AClassical%20Gardens%20of%20Suzhou-111931.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Classical_Gardens_of_Suzhou-111931.jpg/1280px-Classical_Gardens_of_Suzhou-111931.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '南京': [
    { file: '/assets/locations/nanjing-cover-01.jpg', title: '2024Apr - Nanjing City Wall (south section) - img 10.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A2024Apr%20-%20Nanjing%20City%20Wall%20%28south%20section%29%20-%20img%2010.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2024Apr_-_Nanjing_City_Wall_%28south_section%29_-_img_10.jpg/1280px-2024Apr_-_Nanjing_City_Wall_%28south_section%29_-_img_10.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/nanjing-cover-02.jpg', title: '2024Apr - Nanjing City Wall (south section) - img 11.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A2024Apr%20-%20Nanjing%20City%20Wall%20%28south%20section%29%20-%20img%2011.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/2024Apr_-_Nanjing_City_Wall_%28south_section%29_-_img_11.jpg/1280px-2024Apr_-_Nanjing_City_Wall_%28south_section%29_-_img_11.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/nanjing-cover-03.jpg', title: 'Nanjing City Wall 02.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ANanjing%20City%20Wall%2002.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Nanjing_City_Wall_02.jpg/1280px-Nanjing_City_Wall_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '成都': [
    { file: '/assets/locations/chengdu-cover-01.jpg', title: 'Anshun Bridge Chengdu.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AAnshun%20Bridge%20Chengdu.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Anshun_Bridge_Chengdu.jpg/1280px-Anshun_Bridge_Chengdu.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/chengdu-cover-02.jpg', title: 'Anshun Bridge Jin River Chengdu night 2026 dllu.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AAnshun%20Bridge%20Jin%20River%20Chengdu%20night%202026%20dllu.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Anshun_Bridge_Jin_River_Chengdu_night_2026_dllu.jpg/1280px-Anshun_Bridge_Jin_River_Chengdu_night_2026_dllu.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/chengdu-cover-03.jpg', title: 'Anshun Bridge in Chengdu.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AAnshun%20Bridge%20in%20Chengdu.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Anshun_Bridge_in_Chengdu.jpg/1280px-Anshun_Bridge_in_Chengdu.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '厦门': [
    { file: '/assets/locations/xiamen-cover-01.jpg', title: 'A ferry to Gulangyu, Xiamen, China.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AA%20ferry%20to%20Gulangyu%2C%20Xiamen%2C%20China.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/A_ferry_to_Gulangyu%2C_Xiamen%2C_China.JPG/1280px-A_ferry_to_Gulangyu%2C_Xiamen%2C_China.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/xiamen-cover-02.jpg', title: 'Historic district in Gulangyu, Xiamen, China.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AHistoric%20district%20in%20Gulangyu%2C%20Xiamen%2C%20China.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Historic_district_in_Gulangyu%2C_Xiamen%2C_China.JPG/1280px-Historic_district_in_Gulangyu%2C_Xiamen%2C_China.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/xiamen-cover-03.jpg', title: 'Fuzhou Street in Gulangyu Islet, Xiamen, China.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AFuzhou%20Street%20in%20Gulangyu%20Islet%2C%20Xiamen%2C%20China.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Fuzhou_Street_in_Gulangyu_Islet%2C_Xiamen%2C_China.JPG/1280px-Fuzhou_Street_in_Gulangyu_Islet%2C_Xiamen%2C_China.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '北京': [
    { file: '/assets/locations/beijing-forbidden-city.jpg', title: 'The Forbidden City - View from Coal Hill.jpg', landmark: '故宫博物院', sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Forbidden_City_-_View_from_Coal_Hill.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Forbidden_City_-_View_from_Coal_Hill.jpg/1280px-The_Forbidden_City_-_View_from_Coal_Hill.jpg' },
    { file: '/assets/locations/beijing-birds-nest.jpg', title: 'Beijing China Beijing-National-Stadium-01.jpg', landmark: '国家体育场（鸟巢）', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beijing_China_Beijing-National-Stadium-01.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Beijing_China_Beijing-National-Stadium-01.jpg/1280px-Beijing_China_Beijing-National-Stadium-01.jpg' },
    { file: '/assets/locations/beijing-water-cube.jpg', title: 'Lascar The Beijing National Aquatics Center (Water Cube) (4475631690).jpg', landmark: '国家体育场（鸟巢）—水立方', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lascar_The_Beijing_National_Aquatics_Center_(Water_Cube)_(4475631690).jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lascar_The_Beijing_National_Aquatics_Center_%28Water_Cube%29_%284475631690%29.jpg/1280px-Lascar_The_Beijing_National_Aquatics_Center_%28Water_Cube%29_%284475631690%29.jpg' },
    { file: '/assets/locations/beijing-zhajiangmian.jpg', title: 'Zhajiangmian after stirring at Fangzhuanchang (20210115131416).jpg', landmark: '炸酱面', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Zhajiangmian_after_stirring_at_Fangzhuanchang_(20210115131416).jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Zhajiangmian_after_stirring_at_Fangzhuanchang_%2820210115131416%29.jpg/1280px-Zhajiangmian_after_stirring_at_Fangzhuanchang_%2820210115131416%29.jpg' },
    { file: '/assets/locations/beijing-cover-01.jpg', title: 'Pékin Le temple du Ciel.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AP%C3%A9kin%20Le%20temple%20du%20Ciel.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/P%C3%A9kin_Le_temple_du_Ciel.jpg/1280px-P%C3%A9kin_Le_temple_du_Ciel.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/beijing-cover-02.jpg', title: 'Temple of Heaven - Beijing - June 2012.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ATemple%20of%20Heaven%20-%20Beijing%20-%20June%202012.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Temple_of_Heaven_-_Beijing_-_June_2012.jpg/1280px-Temple_of_Heaven_-_Beijing_-_June_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/beijing-cover-03.jpg', title: 'Temple of Heaven, Beijing (March 8 2005).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ATemple%20of%20Heaven%2C%20Beijing%20%28March%208%202005%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Temple_of_Heaven%2C_Beijing_%28March_8_2005%29.jpg/1280px-Temple_of_Heaven%2C_Beijing_%28March_8_2005%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '广州': [
    { file: '/assets/locations/guangzhou-cover-01.jpg', title: 'Canton Tower at night 01.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ACanton%20Tower%20at%20night%2001.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Canton_Tower_at_night_01.jpg/1280px-Canton_Tower_at_night_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/guangzhou-cover-02.jpg', title: 'Guangzhou Tower 20251230.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AGuangzhou%20Tower%2020251230.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Guangzhou_Tower_20251230.jpg/1280px-Guangzhou_Tower_20251230.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/guangzhou-cover-03.jpg', title: 'Canton Tower, Guangzhou (5928597687).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ACanton%20Tower%2C%20Guangzhou%20%285928597687%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Canton_Tower%2C_Guangzhou_%285928597687%29.jpg/1280px-Canton_Tower%2C_Guangzhou_%285928597687%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '重庆': [
    { file: '/assets/locations/chongqing-cover-01.jpg', title: 'Hongya Cave 20180520.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AHongya%20Cave%2020180520.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Hongya_Cave_20180520.jpg/1280px-Hongya_Cave_20180520.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/chongqing-cover-02.jpg', title: 'Hongya Cave 20180520(2).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AHongya%20Cave%2020180520%282%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Hongya_Cave_20180520%282%29.jpg/1280px-Hongya_Cave_20180520%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/chongqing-cover-03.jpg', title: 'Chongqing Nightscape.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AChongqing%20Nightscape.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Chongqing_Nightscape.jpg/1280px-Chongqing_Nightscape.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '西安': [
    { file: '/assets/locations/xian-cover-01.jpg', title: 'XiAn CityWall DiLou.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AXiAn%20CityWall%20DiLou.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/XiAn_CityWall_DiLou.jpg/1280px-XiAn_CityWall_DiLou.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/xian-cover-02.jpg', title: 'XiAn CityWall.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AXiAn%20CityWall.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/XiAn_CityWall.JPG/1280px-XiAn_CityWall.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/xian-cover-03.jpg', title: 'Xi-an city wall side.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AXi-an%20city%20wall%20side.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Xi-an_city_wall_side.jpg/1280px-Xi-an_city_wall_side.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '深圳': [
    { file: '/assets/locations/shenzhen-cover-01.jpg', title: 'Shenzhen Bay Park - 2019-12-09 - 3.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AShenzhen%20Bay%20Park%20-%202019-12-09%20-%203.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Shenzhen_Bay_Park_-_2019-12-09_-_3.jpg/1280px-Shenzhen_Bay_Park_-_2019-12-09_-_3.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shenzhen-cover-02.jpg', title: 'Shenzhen Bay Park - 2019-12-09 - 2.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AShenzhen%20Bay%20Park%20-%202019-12-09%20-%202.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Shenzhen_Bay_Park_-_2019-12-09_-_2.jpg/1280px-Shenzhen_Bay_Park_-_2019-12-09_-_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shenzhen-cover-03.jpg', title: 'Shenzhen Bay Bridge To HK on Shenzhen Side.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AShenzhen%20Bay%20Bridge%20To%20HK%20on%20Shenzhen%20Side.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg/1280px-Shenzhen_Bay_Bridge_To_HK_on_Shenzhen_Side.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '长沙': [
    { file: '/assets/locations/changsha-cover-01.jpg', title: 'Changsha Yuelu 20230723.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AChangsha%20Yuelu%2020230723.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Changsha_Yuelu_20230723.jpg/1280px-Changsha_Yuelu_20230723.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/changsha-cover-02.jpg', title: 'Yuelu Mountain 10832-Changsha (49047505647).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYuelu%20Mountain%2010832-Changsha%20%2849047505647%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Yuelu_Mountain_10832-Changsha_%2849047505647%29.jpg/1280px-Yuelu_Mountain_10832-Changsha_%2849047505647%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/changsha-cover-03.jpg', title: 'Yuelu Mountain 10838-Changsha (49047504952).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYuelu%20Mountain%2010838-Changsha%20%2849047504952%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Yuelu_Mountain_10838-Changsha_%2849047504952%29.jpg/1280px-Yuelu_Mountain_10838-Changsha_%2849047504952%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '青岛': [
    { file: '/assets/locations/qingdao-cover-01.jpg', title: 'Qingdao Zhanqiao.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AQingdao%20Zhanqiao.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Qingdao_Zhanqiao.jpg/1280px-Qingdao_Zhanqiao.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/qingdao-cover-02.jpg', title: '20240729 Zhanqiao 02.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20240729%20Zhanqiao%2002.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/20240729_Zhanqiao_02.jpg/1280px-20240729_Zhanqiao_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/qingdao-cover-03.jpg', title: '20240729 Zhanqiao 01.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20240729%20Zhanqiao%2001.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/20240729_Zhanqiao_01.jpg/1280px-20240729_Zhanqiao_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '武汉': [
    { file: '/assets/locations/wuhan-cover-01.jpg', title: 'Snake Hill from Yellow Crane Tower, Wuhan.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ASnake%20Hill%20from%20Yellow%20Crane%20Tower%2C%20Wuhan.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Snake_Hill_from_Yellow_Crane_Tower%2C_Wuhan.jpg/1280px-Snake_Hill_from_Yellow_Crane_Tower%2C_Wuhan.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/wuhan-cover-02.jpg', title: 'Wuhan.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWuhan.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Wuhan.jpg/1280px-Wuhan.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/wuhan-cover-03.jpg', title: 'YCPViewAcrossYangtze.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYCPViewAcrossYangtze.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/YCPViewAcrossYangtze.jpg/1280px-YCPViewAcrossYangtze.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '昆明': [
    { file: '/assets/locations/kunming-cover-01.jpg', title: '20260222 Kunming Dianchi Lake 03.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260222%20Kunming%20Dianchi%20Lake%2003.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/20260222_Kunming_Dianchi_Lake_03.jpg/1280px-20260222_Kunming_Dianchi_Lake_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/kunming-cover-02.jpg', title: '20260222 Kunming Dianchi Lake.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260222%20Kunming%20Dianchi%20Lake.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/20260222_Kunming_Dianchi_Lake.jpg/1280px-20260222_Kunming_Dianchi_Lake.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/kunming-cover-03.jpg', title: '20260222 Kunming Dianchi Lake 02.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260222%20Kunming%20Dianchi%20Lake%2002.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/20260222_Kunming_Dianchi_Lake_02.jpg/1280px-20260222_Kunming_Dianchi_Lake_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '桂林': [
    { file: '/assets/locations/guilin-cover-01.jpg', title: 'Li river.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ALi%20river.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Li_river.JPG/1280px-Li_river.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/guilin-cover-02.jpg', title: 'Rio li Guilin.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ARio%20li%20Guilin.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Rio_li_Guilin.jpg/1280px-Rio_li_Guilin.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/guilin-cover-03.jpg', title: 'Rio li Guilin02.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ARio%20li%20Guilin02.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Rio_li_Guilin02.jpg/1280px-Rio_li_Guilin02.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '哈尔滨': [
    { file: '/assets/locations/harbin-cover-01.jpg', title: 'Saint Sophia Cathedral, Harbin 06.01.2026.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ASaint%20Sophia%20Cathedral%2C%20Harbin%2006.01.2026.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Saint_Sophia_Cathedral%2C_Harbin_06.01.2026.jpg/1280px-Saint_Sophia_Cathedral%2C_Harbin_06.01.2026.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/harbin-cover-02.jpg', title: 'Saint Sophia Cathedral, Harbin 10.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ASaint%20Sophia%20Cathedral%2C%20Harbin%2010.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Saint_Sophia_Cathedral%2C_Harbin_10.jpg/1280px-Saint_Sophia_Cathedral%2C_Harbin_10.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/harbin-cover-03.jpg', title: 'Harbin Ice & Snow Festival 2026 - Saint Sophia Cathedral.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AHarbin%20Ice%20%26%20Snow%20Festival%202026%20-%20Saint%20Sophia%20Cathedral.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Harbin_Ice_%26_Snow_Festival_2026_-_Saint_Sophia_Cathedral.jpg/1280px-Harbin_Ice_%26_Snow_Festival_2026_-_Saint_Sophia_Cathedral.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '贵阳': [
    { file: '/assets/locations/guiyang-cover-01.jpg', title: 'Jiaxiu Pavilion, Guiyang.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJiaxiu%20Pavilion%2C%20Guiyang.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Jiaxiu_Pavilion%2C_Guiyang.jpg/1280px-Jiaxiu_Pavilion%2C_Guiyang.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/guiyang-cover-02.jpg', title: 'Jiaxiu pavilion.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJiaxiu%20pavilion.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Jiaxiu_pavilion.jpg/1280px-Jiaxiu_pavilion.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/guiyang-cover-03.jpg', title: 'Jiaxiulou 005.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJiaxiulou%20005.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Jiaxiulou_005.jpg/1280px-Jiaxiulou_005.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '张家界': [
    { file: '/assets/locations/zhangjiajie-cover-01.jpg', title: '1 zhangjiajie huangshizhai wulingyuan panorama 2012.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A1%20zhangjiajie%20huangshizhai%20wulingyuan%20panorama%202012.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/1_zhangjiajie_huangshizhai_wulingyuan_panorama_2012.jpg/1280px-1_zhangjiajie_huangshizhai_wulingyuan_panorama_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/zhangjiajie-cover-02.jpg', title: '1 tianzishan wulingyuan zhangjiajie 2012.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A1%20tianzishan%20wulingyuan%20zhangjiajie%202012.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/1_tianzishan_wulingyuan_zhangjiajie_2012.jpg/1280px-1_tianzishan_wulingyuan_zhangjiajie_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/zhangjiajie-cover-03.png', title: 'ChinaZhangjiajieWulingyuan.png', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AChinaZhangjiajieWulingyuan.png', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/ChinaZhangjiajieWulingyuan.png/1280px-ChinaZhangjiajieWulingyuan.png?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '康定': [
    { file: '/assets/locations/kangding-cover-01.jpg', title: 'Kangding-monasterio-nanwu-c01-f.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKangding-monasterio-nanwu-c01-f.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Kangding-monasterio-nanwu-c01-f.jpg/1280px-Kangding-monasterio-nanwu-c01-f.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/kangding-cover-02.jpg', title: 'Kangding-monasterio-nanwu-c05-f.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKangding-monasterio-nanwu-c05-f.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Kangding-monasterio-nanwu-c05-f.jpg/1280px-Kangding-monasterio-nanwu-c05-f.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/kangding-cover-03.jpg', title: 'Kangding-monasterio-nanwu-c06-f.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKangding-monasterio-nanwu-c06-f.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Kangding-monasterio-nanwu-c06-f.jpg/1280px-Kangding-monasterio-nanwu-c06-f.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '稻城亚丁': [
    { file: '/assets/locations/daocheng-yading-cover-01.jpg', title: 'Yading Jampelyang-Yangmaiyong.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYading%20Jampelyang-Yangmaiyong.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Yading%20Jampelyang-Yangmaiyong.jpg?width=1280' },
    { file: '/assets/locations/daocheng-yading-cover-02.jpg', title: 'Yading Chanadorje-Xianuoduoji Chonggu Grassland.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYading%20Chanadorje-Xianuoduoji%20Chonggu%20Grassland.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Yading%20Chanadorje-Xianuoduoji%20Chonggu%20Grassland.jpg?width=1280' },
  ],
  '九寨沟': [
    { file: '/assets/locations/jiuzhaigou-cover-01.jpeg', title: 'Jiuzhaigou Pearl Waterfall 2005-08-21.jpeg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJiuzhaigou%20Pearl%20Waterfall%202005-08-21.jpeg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Jiuzhaigou_Pearl_Waterfall_2005-08-21.jpeg/1280px-Jiuzhaigou_Pearl_Waterfall_2005-08-21.jpeg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/jiuzhaigou-cover-02.jpg', title: 'Jiuzhaigou Valley 20260511.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJiuzhaigou%20Valley%2020260511.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Jiuzhaigou_Valley_20260511.jpg/1280px-Jiuzhaigou_Valley_20260511.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/jiuzhaigou-cover-03.jpg', title: 'Pagodas in in Jiuzhaigou Valley 20260511-1.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3APagodas%20in%20in%20Jiuzhaigou%20Valley%2020260511-1.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Pagodas_in_in_Jiuzhaigou_Valley_20260511-1.jpg/1280px-Pagodas_in_in_Jiuzhaigou_Valley_20260511-1.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '大理': [
    { file: '/assets/locations/dali-cover-01.jpg', title: '20260223 Erhai Park in Dali, Yunnan.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260223%20Erhai%20Park%20in%20Dali%2C%20Yunnan.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/20260223_Erhai_Park_in_Dali%2C_Yunnan.jpg/1280px-20260223_Erhai_Park_in_Dali%2C_Yunnan.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/dali-cover-02.jpg', title: '20260223 Erhai Park in Dali, Yunnan NE.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260223%20Erhai%20Park%20in%20Dali%2C%20Yunnan%20NE.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/20260223_Erhai_Park_in_Dali%2C_Yunnan_NE.jpg/1280px-20260223_Erhai_Park_in_Dali%2C_Yunnan_NE.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/dali-cover-03.jpg', title: '20260223 Erhai Park in Dali, Yunnan NW 03.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A20260223%20Erhai%20Park%20in%20Dali%2C%20Yunnan%20NW%2003.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/20260223_Erhai_Park_in_Dali%2C_Yunnan_NW_03.jpg/1280px-20260223_Erhai_Park_in_Dali%2C_Yunnan_NW_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '丽江': [
    { file: '/assets/locations/lijiang-cover-01.jpg', title: '1 lijiang old town 2012a.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A1%20lijiang%20old%20town%202012a.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/1_lijiang_old_town_2012a.jpg/1280px-1_lijiang_old_town_2012a.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/lijiang-cover-02.jpg', title: '1 lijiang old town night.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A1%20lijiang%20old%20town%20night.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/1_lijiang_old_town_night.jpg/1280px-1_lijiang_old_town_night.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/lijiang-cover-03.jpg', title: 'Oldtownroof.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AOldtownroof.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Oldtownroof.jpg/1280px-Oldtownroof.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '香格里拉': [
    { file: '/assets/locations/shangri-la-cover-01.jpg', title: '松赞林寺 - 全景 - 2025-05-07 09 (cropped).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A%E6%9D%BE%E8%B5%9E%E6%9E%97%E5%AF%BA%20-%20%E5%85%A8%E6%99%AF%20-%202025-05-07%2009%20%28cropped%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/%E6%9D%BE%E8%B5%9E%E6%9E%97%E5%AF%BA_-_%E5%85%A8%E6%99%AF_-_2025-05-07_09_%28cropped%29.jpg/1280px-%E6%9D%BE%E8%B5%9E%E6%9E%97%E5%AF%BA_-_%E5%85%A8%E6%99%AF_-_2025-05-07_09_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shangri-la-cover-02.jpg', title: 'Shangri-La, Yunnan (21007575749).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AShangri-La%2C%20Yunnan%20%2821007575749%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Shangri-La%2C_Yunnan_%2821007575749%29.jpg/1280px-Shangri-La%2C_Yunnan_%2821007575749%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shangri-la-cover-03.jpg', title: 'Shangri-La, Yunnan (20573213103).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AShangri-La%2C%20Yunnan%20%2820573213103%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Shangri-La%2C_Yunnan_%2820573213103%29.jpg/1280px-Shangri-La%2C_Yunnan_%2820573213103%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '西双版纳': [
    { file: '/assets/locations/xishuangbanna-cover-01.jpg', title: 'Water-Splashing Festival, China.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWater-Splashing%20Festival%2C%20China.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Water-Splashing_Festival%2C_China.jpg/1280px-Water-Splashing_Festival%2C_China.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/xishuangbanna-cover-02.jpg', title: 'Dragon Boat race, China.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ADragon%20Boat%20race%2C%20China.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Dragon_Boat_race%2C_China.jpg/1280px-Dragon_Boat_race%2C_China.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/xishuangbanna-cover-03.jpg', title: 'Jinghong Xishuangbanna Daizu Yuan 20250809 091109.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJinghong%20Xishuangbanna%20Daizu%20Yuan%2020250809%20091109.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Jinghong_Xishuangbanna_Daizu_Yuan_20250809_091109.jpg/1280px-Jinghong_Xishuangbanna_Daizu_Yuan_20250809_091109.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '腾冲': [
    { file: '/assets/locations/tengchong-cover-01.jpg', title: 'Rehai 27.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ARehai%2027.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Rehai_27.jpg/1280px-Rehai_27.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/tengchong-cover-02.jpg', title: 'Rehai 23.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ARehai%2023.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Rehai_23.jpg/1280px-Rehai_23.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/tengchong-cover-03.jpg', title: 'Rehai 24.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ARehai%2024.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Rehai_24.jpg/1280px-Rehai_24.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '沈阳': [
    { file: '/assets/locations/shenyang-cover-01.jpg', title: 'Mukden palace gate02.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AMukden%20palace%20gate02.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mukden%20palace%20gate02.jpg?width=1280' },
    { file: '/assets/locations/shenyang-cover-02.jpg', title: 'Palace shenyang.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3APalace%20shenyang.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Palace_shenyang.jpg/1280px-Palace_shenyang.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/shenyang-cover-03.jpg', title: 'Mukden palace gate03.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AMukden%20palace%20gate03.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mukden%20palace%20gate03.jpg?width=1280' },
  ],
  '大连': [
    { file: '/assets/locations/dalian-cover-01.jpg', title: 'Dalian Liaoning China Two-Chinese-at-Xinghai-Bay-01.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ADalian%20Liaoning%20China%20Two-Chinese-at-Xinghai-Bay-01.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Dalian_Liaoning_China_Two-Chinese-at-Xinghai-Bay-01.jpg/1280px-Dalian_Liaoning_China_Two-Chinese-at-Xinghai-Bay-01.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/dalian-cover-02.jpg', title: 'Dalian Xinghai Bay Bridge.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ADalian%20Xinghai%20Bay%20Bridge.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Dalian_Xinghai_Bay_Bridge.jpg/1280px-Dalian_Xinghai_Bay_Bridge.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/dalian-cover-03.jpg', title: 'Dalian China Xinghai-Square-01.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ADalian%20China%20Xinghai-Square-01.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dalian%20China%20Xinghai-Square-01.jpg?width=1280' },
    { file: '/assets/locations/dalian-cover-04.jpg', title: 'Dalian China Xinghai-Square-02.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ADalian%20China%20Xinghai-Square-02.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dalian%20China%20Xinghai-Square-02.jpg?width=1280' },
  ],
  '长春': [
    { file: '/assets/locations/changchun-cover-01.jpg', title: 'Changchun Cultural Square.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AChangchun%20Cultural%20Square.JPG', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Changchun%20Cultural%20Square.JPG?width=1280' },
    { file: '/assets/locations/changchun-cover-02.jpg', title: 'Geological Palace and the Sunbird statue, 2024.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AGeological%20Palace%20and%20the%20Sunbird%20statue%2C%202024.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Geological%20Palace%20and%20the%20Sunbird%20statue%2C%202024.jpg?width=1280' },
  ],
  '延吉': [
    { file: '/assets/locations/yanji-cover-01.jpg', title: 'Yanji city in 2010.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYanji%20city%20in%202010.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Yanji_city_in_2010.jpg/1280px-Yanji_city_in_2010.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/yanji-cover-02.jpg', title: 'Yanji City Center. jpg.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYanji%20City%20Center.%20jpg.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Yanji_City_Center._jpg.jpg/1280px-Yanji_City_Center._jpg.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/yanji-cover-03.jpg', title: 'Yanji city.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AYanji%20city.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Yanji_city.jpg/1280px-Yanji_city.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '漠河': [
    { file: '/assets/locations/mohe-cover-01.png', title: 'October 2024 aurora over Mohe, Heilongjiang.png', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AOctober%202024%20aurora%20over%20Mohe%2C%20Heilongjiang.png', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/October_2024_aurora_over_Mohe%2C_Heilongjiang.png/1280px-October_2024_aurora_over_Mohe%2C_Heilongjiang.png?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/mohe-cover-02.jpeg', title: 'The Most North Of China (184511827).jpeg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AThe%20Most%20North%20Of%20China%20%28184511827%29.jpeg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/The_Most_North_Of_China_%28184511827%29.jpeg/1280px-The_Most_North_Of_China_%28184511827%29.jpeg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '温州': [
    { file: '/assets/locations/wenzhou-cover-01.jpg', title: 'Wenzhou Penjing yuan.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWenzhou%20Penjing%20yuan.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Wenzhou_Penjing_yuan.jpg/1280px-Wenzhou_Penjing_yuan.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/wenzhou-cover-02.jpg', title: 'Wenzhou penjing yuan et Pagode.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AWenzhou%20penjing%20yuan%20et%20Pagode.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Wenzhou_penjing_yuan_et_Pagode.jpg/1280px-Wenzhou_penjing_yuan_et_Pagode.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/wenzhou-cover-03.jpg', title: 'Jiangxin Lighthouse crop.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AJiangxin%20Lighthouse%20crop.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Jiangxin_Lighthouse_crop.jpg/1280px-Jiangxin_Lighthouse_crop.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '台州': [
    { file: '/assets/locations/taizhou-cover-01.jpg', title: '神仙居瀑布 - Waterfall in Shenxianju ScenicSpot - 2014.06 - panoramio.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A%E7%A5%9E%E4%BB%99%E5%B1%85%E7%80%91%E5%B8%83%20-%20Waterfall%20in%20Shenxianju%20ScenicSpot%20-%202014.06%20-%20panoramio.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/%E7%A5%9E%E4%BB%99%E5%B1%85%E7%80%91%E5%B8%83%20-%20Waterfall%20in%20Shenxianju%20ScenicSpot%20-%202014.06%20-%20panoramio.jpg?width=1280' },
    { file: '/assets/locations/taizhou-cover-02.jpg', title: '南天桥 - South Heaven Bridge - 2014.06 - panoramio.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A%E5%8D%97%E5%A4%A9%E6%A1%A5%20-%20South%20Heaven%20Bridge%20-%202014.06%20-%20panoramio.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%8D%97%E5%A4%A9%E6%A1%A5%20-%20South%20Heaven%20Bridge%20-%202014.06%20-%20panoramio.jpg?width=1280' },
    { file: '/assets/locations/taizhou-cover-03.jpg', title: '台州神仙居天桥.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3A%E5%8F%B0%E5%B7%9E%E7%A5%9E%E4%BB%99%E5%B1%85%E5%A4%A9%E6%A1%A5.jpg', downloadUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/%E5%8F%B0%E5%B7%9E%E7%A5%9E%E4%BB%99%E5%B1%85%E5%A4%A9%E6%A1%A5.jpg?width=1280' },
  ],
  '丽水': [
    { file: '/assets/locations/lishui-cover-01.jpg', title: 'Small countryside village, Lishui, China.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ASmall%20countryside%20village%2C%20Lishui%2C%20China.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Small_countryside_village%2C_Lishui%2C_China.jpg/1280px-Small_countryside_village%2C_Lishui%2C_China.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/lishui-cover-02.jpg', title: 'Countryside village in Lishui, China.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ACountryside%20village%20in%20Lishui%2C%20China.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Countryside_village_in_Lishui%2C_China.jpg/1280px-Countryside_village_in_Lishui%2C_China.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/lishui-cover-03.jpg', title: 'Countryside views in Lishui, China.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ACountryside%20views%20in%20Lishui%2C%20China.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Countryside_views_in_Lishui%2C_China.jpg/1280px-Countryside_views_in_Lishui%2C_China.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '乌鲁木齐': [
    { file: '/assets/locations/urumqi-cover-01.jpg', title: 'Place of worship for Hui minority of Han Chinese Muslims near the Urumqi International Grand Bazaar in 2012.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3APlace%20of%20worship%20for%20Hui%20minority%20of%20Han%20Chinese%20Muslims%20near%20the%20Urumqi%20International%20Grand%20Bazaar%20in%202012.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Place_of_worship_for_Hui_minority_of_Han_Chinese_Muslims_near_the_Urumqi_International_Grand_Bazaar_in_2012.jpg/1280px-Place_of_worship_for_Hui_minority_of_Han_Chinese_Muslims_near_the_Urumqi_International_Grand_Bazaar_in_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/urumqi-cover-02.jpg', title: 'Bazaar day time.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ABazaar%20day%20time.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Bazaar_day_time.jpg/1280px-Bazaar_day_time.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/urumqi-cover-03.jpg', title: 'DSC - Urumqi Bazaar Guardians.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ADSC%20-%20Urumqi%20Bazaar%20Guardians.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/DSC_-_Urumqi_Bazaar_Guardians.jpg/1280px-DSC_-_Urumqi_Bazaar_Guardians.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '喀什': [
    { file: '/assets/locations/kashgar-cover-01.jpg', title: 'Kashgar Old City (crop).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKashgar%20Old%20City%20%28crop%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Kashgar_Old_City_%28crop%29.jpg/1280px-Kashgar_Old_City_%28crop%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/kashgar-cover-02.jpg', title: 'Kashgar-casco-viejo-d01.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKashgar-casco-viejo-d01.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kashgar-casco-viejo-d01.jpg/1280px-Kashgar-casco-viejo-d01.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/kashgar-cover-03.jpg', title: 'Kashgar-casco-viejo-d07.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKashgar-casco-viejo-d07.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Kashgar-casco-viejo-d07.jpg/1280px-Kashgar-casco-viejo-d07.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '拉萨': [
    { file: '/assets/locations/lhasa-cover-01.jpg', title: 'Lhasa from Potala place.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ALhasa%20from%20Potala%20place.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Lhasa_from_Potala_place.JPG/1280px-Lhasa_from_Potala_place.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/lhasa-cover-02.jpg', title: 'Lhasa from Potala-2.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ALhasa%20from%20Potala-2.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Lhasa_from_Potala-2.jpg/1280px-Lhasa_from_Potala-2.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/lhasa-cover-03.jpg', title: 'Lhasa from Potala.JPG', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ALhasa%20from%20Potala.JPG', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Lhasa_from_Potala.JPG/1280px-Lhasa_from_Potala.JPG?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
  '林芝': [
    { file: '/assets/locations/nyingchi-cover-01.jpg', title: 'Puqu Township, Bayi, Nyingchi Tibet (49993581418).jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3APuqu%20Township%2C%20Bayi%2C%20Nyingchi%20Tibet%20%2849993581418%29.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Puqu_Township%2C_Bayi%2C_Nyingchi_Tibet_%2849993581418%29.jpg/1280px-Puqu_Township%2C_Bayi%2C_Nyingchi_Tibet_%2849993581418%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/nyingchi-cover-02.jpg', title: 'King Cypress Tree.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3AKing%20Cypress%20Tree.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/King_Cypress_Tree.jpg/1280px-King_Cypress_Tree.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
    { file: '/assets/locations/nyingchi-cover-03.jpg', title: 'Nyingchi, Tibet - 42364647972.jpg', sourceUrl: 'https://commons.wikimedia.org/wiki/File%3ANyingchi%2C%20Tibet%20-%2042364647972.jpg', downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Nyingchi%2C_Tibet_-_42364647972.jpg/1280px-Nyingchi%2C_Tibet_-_42364647972.jpg?utm_source=commons.wikimedia.org&utm_campaign=rest&utm_content=thumbnail' },
  ],
}

const coverLandmarks: Record<string, string> = {
  '/assets/locations/shanghai-cover-01.jpg': '武康路',
  '/assets/locations/shanghai-cover-02.jpg': '武康路',
  '/assets/locations/shanghai-cover-03.jpg': '武康路',
  '/assets/locations/hangzhou-cover-01.jpg': '西湖',
  '/assets/locations/hangzhou-cover-02.jpg': '西湖',
  '/assets/locations/hangzhou-cover-03.jpg': '西湖',
  '/assets/locations/suzhou-cover-01.jpg': '苏州园林',
  '/assets/locations/suzhou-cover-02.jpg': '苏州园林',
  '/assets/locations/suzhou-cover-03.jpg': '苏州园林',
  '/assets/locations/nanjing-cover-01.jpg': '南京城墙',
  '/assets/locations/nanjing-cover-02.jpg': '南京城墙',
  '/assets/locations/nanjing-cover-03.jpg': '南京城墙',
  '/assets/locations/chengdu-cover-01.jpg': '安顺廊桥',
  '/assets/locations/chengdu-cover-02.jpg': '安顺廊桥',
  '/assets/locations/chengdu-cover-03.jpg': '安顺廊桥',
  '/assets/locations/xiamen-cover-01.jpg': '鼓浪屿',
  '/assets/locations/xiamen-cover-02.jpg': '鼓浪屿',
  '/assets/locations/xiamen-cover-03.jpg': '鼓浪屿',
  '/assets/locations/beijing-cover-01.jpg': '天坛公园',
  '/assets/locations/beijing-cover-02.jpg': '天坛公园',
  '/assets/locations/beijing-cover-03.jpg': '天坛公园',
  '/assets/locations/guangzhou-cover-01.jpg': '广州塔',
  '/assets/locations/guangzhou-cover-02.jpg': '广州塔',
  '/assets/locations/guangzhou-cover-03.jpg': '广州塔',
  '/assets/locations/chongqing-cover-01.jpg': '洪崖洞',
  '/assets/locations/chongqing-cover-02.jpg': '洪崖洞',
  '/assets/locations/chongqing-cover-03.jpg': '重庆夜景',
  '/assets/locations/xian-cover-01.jpg': '西安城墙',
  '/assets/locations/xian-cover-02.jpg': '西安城墙',
  '/assets/locations/xian-cover-03.jpg': '西安城墙',
  '/assets/locations/shenzhen-cover-01.jpg': '深圳湾公园',
  '/assets/locations/shenzhen-cover-02.jpg': '深圳湾公园',
  '/assets/locations/shenzhen-cover-03.jpg': '深圳湾大桥',
  '/assets/locations/changsha-cover-01.jpg': '岳麓山',
  '/assets/locations/changsha-cover-02.jpg': '岳麓山',
  '/assets/locations/changsha-cover-03.jpg': '岳麓山',
  '/assets/locations/qingdao-cover-01.jpg': '栈桥',
  '/assets/locations/qingdao-cover-02.jpg': '栈桥',
  '/assets/locations/qingdao-cover-03.jpg': '栈桥',
  '/assets/locations/wuhan-cover-01.jpg': '黄鹤楼',
  '/assets/locations/kunming-cover-01.jpg': '滇池',
  '/assets/locations/kunming-cover-02.jpg': '滇池',
  '/assets/locations/kunming-cover-03.jpg': '滇池',
  '/assets/locations/guilin-cover-01.jpg': '漓江',
  '/assets/locations/guilin-cover-02.jpg': '漓江',
  '/assets/locations/guilin-cover-03.jpg': '漓江',
  '/assets/locations/harbin-cover-01.jpg': '圣索菲亚教堂',
  '/assets/locations/harbin-cover-02.jpg': '圣索菲亚教堂',
  '/assets/locations/harbin-cover-03.jpg': '圣索菲亚教堂',
  '/assets/locations/guiyang-cover-01.jpg': '甲秀楼',
  '/assets/locations/guiyang-cover-02.jpg': '甲秀楼',
  '/assets/locations/guiyang-cover-03.jpg': '甲秀楼',
  '/assets/locations/zhangjiajie-cover-01.jpg': '黄石寨',
  '/assets/locations/zhangjiajie-cover-02.jpg': '天子山',
  '/assets/locations/zhangjiajie-cover-03.png': '武陵源',
  '/assets/locations/daocheng-yading-cover-01.jpg': '央迈勇',
  '/assets/locations/daocheng-yading-cover-02.jpg': '冲古草甸',
  '/assets/locations/jiuzhaigou-cover-01.jpeg': '珍珠滩瀑布',
  '/assets/locations/jiuzhaigou-cover-02.jpg': '九寨沟',
  '/assets/locations/jiuzhaigou-cover-03.jpg': '九寨沟',
  '/assets/locations/lijiang-cover-01.jpg': '丽江古城',
  '/assets/locations/lijiang-cover-02.jpg': '丽江古城',
  '/assets/locations/lijiang-cover-03.jpg': '丽江古城',
  '/assets/locations/shangri-la-cover-01.jpg': '松赞林寺',
  '/assets/locations/shangri-la-cover-02.jpg': '香格里拉',
  '/assets/locations/shangri-la-cover-03.jpg': '香格里拉',
  '/assets/locations/xishuangbanna-cover-03.jpg': '傣族园',
  '/assets/locations/tengchong-cover-01.jpg': '热海景区',
  '/assets/locations/tengchong-cover-02.jpg': '热海景区',
  '/assets/locations/tengchong-cover-03.jpg': '热海景区',
  '/assets/locations/shenyang-cover-01.jpg': '沈阳故宫',
  '/assets/locations/shenyang-cover-02.jpg': '沈阳故宫',
  '/assets/locations/shenyang-cover-03.jpg': '沈阳故宫',
  '/assets/locations/dalian-cover-01.jpg': '星海湾',
  '/assets/locations/dalian-cover-02.jpg': '星海湾大桥',
  '/assets/locations/dalian-cover-03.jpg': '星海广场',
  '/assets/locations/dalian-cover-04.jpg': '星海广场',
  '/assets/locations/mohe-cover-02.jpeg': '北极村',
  '/assets/locations/wenzhou-cover-03.jpg': '江心屿',
  '/assets/locations/taizhou-cover-01.jpg': '神仙居',
  '/assets/locations/taizhou-cover-02.jpg': '南天桥',
  '/assets/locations/taizhou-cover-03.jpg': '神仙居',
  '/assets/locations/urumqi-cover-01.jpg': '国际大巴扎',
  '/assets/locations/urumqi-cover-02.jpg': '国际大巴扎',
  '/assets/locations/urumqi-cover-03.jpg': '国际大巴扎',
  '/assets/locations/kashgar-cover-01.jpg': '喀什古城',
  '/assets/locations/kashgar-cover-02.jpg': '喀什古城',
  '/assets/locations/kashgar-cover-03.jpg': '喀什古城',
  '/assets/locations/lhasa-cover-01.jpg': '布达拉宫',
  '/assets/locations/lhasa-cover-02.jpg': '布达拉宫',
  '/assets/locations/lhasa-cover-03.jpg': '布达拉宫',
}

export const cityCoverImages: Record<string, CityImage[]> = Object.fromEntries(
  Object.entries(cityCoverSeeds).map(([city, seeds]) => [city, seeds.map((seed) => ({
    src: seed.file,
    alt: `${city}${seed.title.replace(/\.(jpe?g|png|webp)$/i, '')}特色风景`,
    landmark: seed.landmark ?? coverLandmarks[seed.file] ?? seed.title.replace(/\.(jpe?g|png|webp)$/i, ''),
    sourceUrl: seed.sourceUrl,
    credit: 'Wikimedia Commons contributors',
    license: '以来源页标注为准',
    licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia',
    downloadUrl: seed.downloadUrl,
  }))]),
)
